apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: k8s-quickstart
build:
  artifacts:
  - image: web
    context: ./apps/web
    docker:
      dockerfile: dockerfile
  - image: user
    context: ./apps/user
    docker:
      dockerfile: dockerfile
deploy:
  kubectl:
    manifests:
    - /kubernetes/k8s-quickstart.yml
