apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: k8s-quickstart
build:
  artifacts:
  - image: web
    docker:
      dockerfile: web.Dockerfile
  - image: user
    docker:
      dockerfile: user.Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/k8s-quickstart.yml
