apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: k8s-quickstart
build:
  artifacts:
  - image: hello
    docker:
      dockerfile: hello.Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/quickstart.yml
