apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: k8s-quickstart
build:
  artifacts:
#  - image: userapi
#    context: ./apps/userapi
#    docker:
#      dockerfile: dockerfile
  - image: reactapp
    context: ./apps/reactapp
    docker:
      dockerfile: dockerfile
manifests:
  rawYaml:
      - kubernetes/gateway.yml
  helm:
    releases:
      - name: reactapp
        chartPath: helm/reactapp
        valuesFiles:
          - helm/reactapp/values.yaml
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
  
#  helm:
#    releases:
#      - name: userapi
#        chartPath: helm/userapi
#        valuesFiles:
#          - helm/userapi/values.yaml
#      - name: reactapp
#        chartPath: helm/reactapp
#        valuesFiles:
#          - helm/reactapp/values.yaml
