apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reactapp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "reactapp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "reactapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "reactapp.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "reactapp.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"