apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: reactapp
  namespace: {{ .Values.namespace }}
spec:
  hostnames: ["local.k8s-demo.com"]
  parentRefs:
  - name: gateway
    namespace: istio-ingress
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: reactapp
      port: 8000