apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactapp.fullname" . }}
  labels:
    {{- include "reactapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "reactapp.selectorLabels" . | nindent 4 }}